version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    network_mode: host
  agebox:
    image: "trueface/agebox:latest"
    ports:
      - "9000:8080"
    environment:
        - TOKEN